version: 2.1

jobs:
  ubuntu_arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/conda_asan.sh
        environment:
          CONDA_INSTALLER_ARCH: Linux-aarch64

workflows:
  version: 2.1
  all_builds:
    jobs:
    - ubuntu_arm64
