name: GitHub CI
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
jobs:
  conda_asan:
    runs-on: ubuntu-latest
    env:
      CONDA_INSTALLER_ARCH: Linux-x86_64
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash tools/conda_asan.sh
  osx_14_arm64:
    runs-on: macos-14
    env:
      CONDA_INSTALLER_ARCH: MacOSX-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash tools/conda.sh
